- menu_name: "Links"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "About"
  url: "/info/"
  title: "About Us"

- name: "Privacy Policy"
  url: "/privacy/"
  title: "Privacy Policy"

- name: "Terms"
  url: "/TOS/"
  title: "Terms of Service"

- name: "Cookies"
  url: "/Cookie/"
  title: "Cookie Policy"
